<?php

namespace Database\Seeders;

use App\Models\Guru;
use Illuminate\Database\Seeder;

class DataEksternalSeeder extends Seeder
{
    public function run(): void
    {
        foreach ([
            [
                'no_ktp' => '7372761008840009',
                'nama_lengkap' => 'Andi Nurul Fadilah, S.Pd., M.Pd.',
                'username' => 'andhinurulfadilah',
                'email' => 'andi.nurul.fadilah@kemdikbud.go.id',
                'nip' => '197906152006042001',
                'tempat_lahir' => 'Parepare',
                'tgl_lahir' => '1979-06-15',
                'gender' => 'Perempuan',
                'jabatan' => 'Kepala Sekolah',
                'status' => 'Kawin',
                'status_kepegawaian' => 'PNS',
                'agama' => 'Islam',
                'pendidikan' => 'S2',
                'kabupaten' => 'Kota Parepare',
                'satuan_pendidikan' => 'SMP Negeri',
                'alamat_satuan' => 'Jalan Bau Massepe Nomor 7, Kota Parepare',
                'alamat_rumah' => 'Jalan Mattirotasi, Kecamatan Ujung, Kota Parepare',
                'no_hp' => '081355840009',
                'no_wa' => '081355840009',
                'pas_foto' => '',
                'no_rek' => '0201011979061509',
                'jenis_bank' => 'Bank BRI',
                'npsn_sekolah' => '40307676',
                'npwp' => '917350619760009',
                'nuptk' => '1979061520010009',
                'eksternal_jabatan' => 'Tenaga Kependidikan',
                'jenis_jabatan' => 'Kepala Sekolah',
                'kategori_jabatan' => 'GP (Guru Penggerak)',
                'tugas_jabatan' => 'PP (Pengajar Praktik)',
                'latar_jabatan' => 'Diklat Cakep',
                'is_verif' => 'sudah',
            ],
            [
                'no_ktp' => '7373021809870010',
                'nama_lengkap' => 'Nur Aulia Ramadhani, S.Pd.',
                'username' => 'nur.aulia.ramadhani',
                'email' => 'nur.aulia.ramadhani@sekolah.test',
                'nip' => '198709182014022001',
                'tempat_lahir' => 'Makassar',
                'tgl_lahir' => '1987-09-18',
                'gender' => 'Perempuan',
                'jabatan' => 'Guru Bahasa Indonesia',
                'status' => 'Kawin',
                'status_kepegawaian' => 'PNS',
                'agama' => 'Islam',
                'pendidikan' => 'S1',
                'kabupaten' => 'Kota Parepare',
                'satuan_pendidikan' => 'SMP Negeri',
                'alamat_satuan' => 'Jalan Bau Massepe Nomor 7, Kota Parepare',
                'alamat_rumah' => 'Jalan Jenderal Sudirman, Kota Parepare',
                'no_hp' => '081355840010',
                'no_wa' => '081355840010',
                'pas_foto' => '',
                'no_rek' => '0201011987091810',
                'jenis_bank' => 'Bank BNI',
                'npsn_sekolah' => '40307676',
                'npwp' => '917350619870010',
                'nuptk' => '198709182014022010',
                'eksternal_jabatan' => 'Tenaga Pendidik',
                'jenis_jabatan' => 'Guru',
                'kategori_jabatan' => 'GP (Guru Penggerak)',
                'tugas_jabatan' => 'Fasil (Fasilitator)',
                'latar_jabatan' => 'Sertifikat GP (Guru Penggerak)',
                'is_verif' => 'sudah',
            ],
            [
                'no_ktp' => '7373012510820011',
                'nama_lengkap' => 'Muhammad Fikri Latif, S.Pd.',
                'username' => 'muhammad.fikri.latif',
                'email' => 'muhammad.fikri.latif@sekolah.test',
                'nip' => '198210252009011001',
                'tempat_lahir' => 'Sungguminasa',
                'tgl_lahir' => '1982-10-25',
                'gender' => 'Laki-laki',
                'jabatan' => 'Guru Matematika',
                'status' => 'Kawin',
                'status_kepegawaian' => 'PNS',
                'agama' => 'Islam',
                'pendidikan' => 'S1',
                'kabupaten' => 'Kota Parepare',
                'satuan_pendidikan' => 'SMA Negeri',
                'alamat_satuan' => 'Jalan Karaeng Burane Nomor 18, Kota Parepare',
                'alamat_rumah' => 'Jalan Andi Makkasau, Kota Parepare',
                'no_hp' => '081355840011',
                'no_wa' => '081355840011',
                'pas_foto' => '',
                'no_rek' => '0201011982102511',
                'jenis_bank' => 'Bank Mandiri',
                'npsn_sekolah' => '40307693',
                'npwp' => '917350619820011',
                'nuptk' => '198210252009011011',
                'eksternal_jabatan' => 'Tenaga Pendidik',
                'jenis_jabatan' => 'Guru',
                'kategori_jabatan' => 'GP (Guru Penggerak)',
                'tugas_jabatan' => 'PP (Pengajar Praktik)',
                'latar_jabatan' => 'Sertifikat GP (Guru Penggerak)',
                'is_verif' => 'sudah',
            ],
            [
                'no_ktp' => '7371090701760012',
                'nama_lengkap' => 'Abdul Rahman Basri, S.Pd., M.Si.',
                'username' => 'abdul.rahman.basri',
                'email' => 'abdul.rahman.basri@pengawas.test',
                'nip' => '197601072000121002',
                'tempat_lahir' => 'Maros',
                'tgl_lahir' => '1976-01-07',
                'gender' => 'Laki-laki',
                'jabatan' => 'Pengawas Sekolah',
                'status' => 'Kawin',
                'status_kepegawaian' => 'PNS',
                'agama' => 'Islam',
                'pendidikan' => 'S2',
                'kabupaten' => 'Kabupaten Maros',
                'satuan_pendidikan' => 'Dinas Pendidikan Provinsi Sulawesi Selatan',
                'alamat_satuan' => 'Jalan Perintis Kemerdekaan, Makassar',
                'alamat_rumah' => 'Jalan Azalea, Turikale, Maros',
                'no_hp' => '081355840012',
                'no_wa' => '081355840012',
                'pas_foto' => '',
                'no_rek' => '0201011976010712',
                'jenis_bank' => 'Bank Syariah Indonesia',
                'npsn_sekolah' => '-',
                'npwp' => '917350619760012',
                'nuptk' => '197601072000121012',
                'eksternal_jabatan' => 'Tenaga Kependidikan',
                'jenis_jabatan' => 'Pengawas',
                'kategori_jabatan' => 'NoN GP (Guru Penggerak)',
                'tugas_jabatan' => '',
                'latar_jabatan' => 'Lainnya',
                'is_verif' => 'sudah',
            ],
        ] as $guru) {
            Guru::updateOrCreate(['no_ktp' => $guru['no_ktp']], $guru);
        }
    }
}
