<?php

namespace Database\Seeders;

use App\Models\Sekolah;
use App\Models\User;
use Illuminate\Database\Seeder;

class DataSekolahSeeder extends Seeder
{
    public function run(): void
    {
        $kepalaUserId = User::where('no_ktp', '7372761008840009')->value('id');

        foreach ([
            [
                'nama_sekolah' => 'UPTD SD NEGERI 1 PAREPARE',
                'npsn_sekolah' => '40307724',
                'bp_sekolah' => 'SD',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
                'alamat' => 'Jalan Veteran Nomor 45, Kota Parepare',
                'akreditasi' => 'A',
                'no_telepon' => '(0421) 21123',
                'email' => 'sdn1parepare@kemdikbud.go.id',
                'tahun_berdiri' => '1952',
                'nama_kepsek' => 'Andi Nurul Fadilah, S.Pd., M.Pd.',
                'asn_opsi' => 'ya',
                'nip_kepsek' => '197906152006042001',
                'no_sk' => '821.2/114/Disdik/2024',
                'no_telp_kepsek' => '081355840009',
                'email_kepsek' => 'kepala.sdn1parepare@kemdikbud.go.id',
                'jumlah_guru' => 28,
                'jumlah_guru_pns' => 20,
                'jumlah_honorer' => 8,
                'jumlah_kependidikan' => 7,
                'bidang_studi' => 'Guru kelas, Pendidikan Agama Islam, Pendidikan Jasmani, Bahasa Inggris',
                'jumlah_siswa' => 384,
                'jumlah_siswa_pria' => 196,
                'jumlah_siswa_perempuan' => 188,
                'jumlah_siswa_per_kelas' => '32 siswa per rombongan belajar',
                'jumlah_kelas' => 12,
                'laboratorium' => 'Laboratorium komputer',
                'perpustakaan' => 'Perpustakaan sekolah',
                'ruang_guru' => 'Tersedia',
                'jumlah_toilet' => 12,
                'lapangan_olahraga' => 'Lapangan olahraga serbaguna',
                'fasilitas_it' => ['Komputer', 'Proyektor', 'Internet sekolah'],
                'fasilitas_it_tambahan' => 'Chromebook untuk pembelajaran digital',
                'akses_internet' => 'Fiber optik',
                'ekstrakurikuler' => 'Pramuka, Palang Merah Remaja, seni tari, olahraga',
                'program_unggulan' => 'Literasi sekolah dan numerasi kontekstual',
                'jam_belajar' => '07:30–13:30 WITA',
            ],
            [
                'nama_sekolah' => 'UPTD SMP NEGERI 1 PAREPARE',
                'npsn_sekolah' => '40307676',
                'bp_sekolah' => 'SMP',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
                'alamat' => 'Jalan Bau Massepe Nomor 7, Kota Parepare',
                'akreditasi' => 'A',
                'no_telepon' => '(0421) 21456',
                'email' => 'smpn1parepare@kemdikbud.go.id',
                'tahun_berdiri' => '1960',
                'nama_kepsek' => 'Andi Nurul Fadilah, S.Pd., M.Pd.',
                'asn_opsi' => 'ya',
                'nip_kepsek' => '197906152006042001',
                'no_sk' => '821.2/115/Disdik/2024',
                'no_telp_kepsek' => '081355840009',
                'email_kepsek' => 'kepala.smpn1parepare@kemdikbud.go.id',
                'jumlah_guru' => 42,
                'jumlah_guru_pns' => 31,
                'jumlah_honorer' => 11,
                'jumlah_kependidikan' => 9,
                'bidang_studi' => 'Bahasa Indonesia, Matematika, IPA, IPS, Bahasa Inggris, Informatika',
                'jumlah_siswa' => 672,
                'jumlah_siswa_pria' => 344,
                'jumlah_siswa_perempuan' => 328,
                'jumlah_siswa_per_kelas' => '32 siswa per rombongan belajar',
                'jumlah_kelas' => 21,
                'laboratorium' => 'Laboratorium IPA dan komputer',
                'perpustakaan' => 'Perpustakaan digital',
                'ruang_guru' => 'Tersedia',
                'jumlah_toilet' => 18,
                'lapangan_olahraga' => 'Lapangan basket dan voli',
                'fasilitas_it' => ['Komputer', 'Proyektor', 'Internet sekolah', 'Papan interaktif'],
                'fasilitas_it_tambahan' => 'Ruang multimedia',
                'akses_internet' => 'Fiber optik',
                'ekstrakurikuler' => 'Pramuka, OSIS, PMR, KIR, futsal, paduan suara',
                'program_unggulan' => 'Sekolah adiwiyata dan komunitas belajar guru',
                'jam_belajar' => '07:15–14:15 WITA',
            ],
            [
                'nama_sekolah' => 'SMA NEGERI 1 PAREPARE',
                'npsn_sekolah' => '40307693',
                'bp_sekolah' => 'SMA',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
                'alamat' => 'Jalan Karaeng Burane Nomor 18, Kota Parepare',
                'akreditasi' => 'A',
                'no_telepon' => '(0421) 21890',
                'email' => 'sman1parepare@kemdikbud.go.id',
                'tahun_berdiri' => '1958',
                'nama_kepsek' => 'Andi Nurul Fadilah, S.Pd., M.Pd.',
                'asn_opsi' => 'ya',
                'nip_kepsek' => '197906152006042001',
                'no_sk' => '821.2/116/Disdik/2024',
                'no_telp_kepsek' => '081355840009',
                'email_kepsek' => 'kepala.sman1parepare@kemdikbud.go.id',
                'jumlah_guru' => 55,
                'jumlah_guru_pns' => 45,
                'jumlah_honorer' => 10,
                'jumlah_kependidikan' => 12,
                'bidang_studi' => 'Matematika, Fisika, Kimia, Biologi, Bahasa, IPS, Informatika',
                'jumlah_siswa' => 840,
                'jumlah_siswa_pria' => 390,
                'jumlah_siswa_perempuan' => 450,
                'jumlah_siswa_per_kelas' => '35 siswa per rombongan belajar',
                'jumlah_kelas' => 24,
                'laboratorium' => 'Laboratorium fisika, kimia, biologi, dan komputer',
                'perpustakaan' => 'Perpustakaan sekolah',
                'ruang_guru' => 'Tersedia',
                'jumlah_toilet' => 24,
                'lapangan_olahraga' => 'Lapangan olahraga terpadu',
                'fasilitas_it' => ['Komputer', 'Proyektor', 'Internet sekolah'],
                'fasilitas_it_tambahan' => 'Studio produksi media pembelajaran',
                'akses_internet' => 'Fiber optik',
                'ekstrakurikuler' => 'Pramuka, debat, olahraga, jurnalistik, seni musik',
                'program_unggulan' => 'Riset siswa dan persiapan masuk perguruan tinggi',
                'jam_belajar' => '07:15–15:00 WITA',
            ],
            [
                'nama_sekolah' => 'SMK NEGERI 3 PAREPARE',
                'npsn_sekolah' => '40307698',
                'bp_sekolah' => 'SMK',
                'status_sekolah' => 'Negeri',
                'kecamatan' => 'Kecamatan Ujung',
                'kabupaten' => 'Kota Parepare',
                'alamat' => 'Jalan Pendidikan Nomor 3, Kota Parepare',
                'akreditasi' => 'A',
                'no_telepon' => '(0421) 22991',
                'email' => 'smkn3parepare@kemdikbud.go.id',
                'tahun_berdiri' => '2004',
                'nama_kepsek' => 'Andi Nurul Fadilah, S.Pd., M.Pd.',
                'asn_opsi' => 'ya',
                'nip_kepsek' => '197906152006042001',
                'no_sk' => '821.2/117/Disdik/2024',
                'no_telp_kepsek' => '081355840009',
                'email_kepsek' => 'kepala.smkn3parepare@kemdikbud.go.id',
                'jumlah_guru' => 48,
                'jumlah_guru_pns' => 34,
                'jumlah_honorer' => 14,
                'jumlah_kependidikan' => 11,
                'bidang_studi' => 'Teknik jaringan, rekayasa perangkat lunak, tata boga, dan otomotif',
                'jumlah_siswa' => 720,
                'jumlah_siswa_pria' => 468,
                'jumlah_siswa_perempuan' => 252,
                'jumlah_siswa_per_kelas' => '36 siswa per rombongan belajar',
                'jumlah_kelas' => 20,
                'laboratorium' => 'Bengkel praktik dan laboratorium komputer',
                'perpustakaan' => 'Perpustakaan sekolah',
                'ruang_guru' => 'Tersedia',
                'jumlah_toilet' => 20,
                'lapangan_olahraga' => 'Lapangan futsal dan voli',
                'fasilitas_it' => ['Komputer', 'Proyektor', 'Internet sekolah'],
                'fasilitas_it_tambahan' => 'Peralatan praktik berbasis industri',
                'akses_internet' => 'Fiber optik',
                'ekstrakurikuler' => 'Pramuka, kewirausahaan, olahraga, dan seni',
                'program_unggulan' => 'Teaching factory dan sertifikasi kompetensi',
                'jam_belajar' => '07:15–15:30 WITA',
            ],
        ] as $school) {
            Sekolah::updateOrCreate(
                ['npsn_sekolah' => $school['npsn_sekolah']],
                $school + [
                    'user_id' => $kepalaUserId,
                    'provinsi' => 'SULAWESI SELATAN',
                    'koordinat' => '-4.0167, 119.6236',
                    'no_sk' => $school['no_sk'],
                ]
            );
        }
    }
}
